name: Podcast generator

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v4

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Run feed generator
        run: sverma092@podcast-generator@main